name: todoit
description: Learning flutter by doing.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.3.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

# https://docs.flutter.dev/cookbook/design/fonts
fonts:
  - family: OpenSans
    fonts:
    - asset: assets/fonts/OpenSans-Regular.ttf
      weight: 400
    - asset: assets/fonts/OpenSans-Bold.ttf
      weight: 700
    - asset: assets/fonts/OpenSans-Light.ttf
      weight: 300